import { useMemo, useState } from "react";

const stages = [
  { nav: "KPI Foundation", eyebrow: "Chapter 01 — The Scoreboard", title: <>We start with the <em>executive outcomes.</em></>, body: "Before a single campaign is built, a segment is defined, or a dashboard is configured, we align on what the business is actually trying to accomplish. The KPI framework becomes the operating system for every marketing, sales, and customer motion that follows.", quote: "Before we build the strategy, we define the scoreboard. What does the executive team need to move? Revenue? Market share? Customer acquisition? Expansion? Profitability? Every segment, campaign, sales motion, and customer action will be measured against these outcomes." },
  { nav: "Growth Objective", eyebrow: "Chapter 02 — The Growth Question", title: <>What are we growing? <em>And for whom?</em></>, body: "Once the KPI framework is clear, we define the growth objective and the audience behind it. Strategy becomes sharper when these two questions are answered together — because the motion required to grow revenue through acquisition is fundamentally different from the motion required to grow it through expansion.", quote: "The question is not just 'What do we want to grow?' It is also 'Who do we need to move in order to grow it?' These two questions define the entire system architecture." },
  { nav: "Segmentation", eyebrow: "Chapter 03 — Segmentation", title: <>Turn a broad market into <em>actionable groups.</em></>, body: "Segmentation is the first intelligence layer underneath the dashboard. It tells us who we are speaking to, what they care about, how they buy, and where the largest opportunities exist. Without segmentation, every campaign and sales motion is generic by default.", quote: "Segmentation turns a broad market into actionable groups. It tells us who we are speaking to, what they care about, how they buy, and where the largest opportunities exist." },
  { nav: "Total Addressable Market", eyebrow: "Chapter 04 — Total Addressable Market", title: <>Map the full <em>market opportunity.</em></>, body: "Once segments are defined, we map the Total Addressable Market for each one. This is how the executive team begins to understand market share, whitespace, and where growth is still available. The TAM layer answers the questions a dashboard alone cannot.", quote: "How many companies are in the addressable market? Which ones are already customers? Which ones are prospects? Where do we have share? Where do we have whitespace? And who are the contacts we need to reach?" },
  { nav: "Personas", eyebrow: "Chapter 05 — Personas", title: <>Build personas from <em>real opportunity,</em> not assumptions.</>, body: "Personas are built from actual customer segments and market opportunity — not templates. Each one represents a real buyer role inside the accounts we've already identified, with a specific message, motion, and conversion barrier unique to their priorities.", quote: "Once we know the segments and the addressable market, we can build personas that are grounded in real commercial opportunity." },
  { nav: "Customer Tiering", eyebrow: "Chapter 06 — Customer Value Tiering", title: <>Every customer has a <em>next move.</em></>, body: "For current customers, the goal is not only retention. The goal is expansion. We use customer value, purchase behavior, product fit, and growth potential to determine which customers can move up — and build a motion specific to how each segment needs to be spoken to.", quote: "We use customer value, purchase behavior, product fit, and growth potential to understand which customers can move from Tier 3 to Tier 2, or from Tier 2 to Tier 1." },
  { nav: "Prospect Funnel", eyebrow: "Chapter 07 — Prospect Funnel", title: <>Turn market opportunity into <em>qualified pipeline.</em></>, body: "For prospects, the goal is to convert TAM into pipeline. We use segmentation, TAM fit, intent signals, and engagement data to prioritize who marketing should target and who sales should pursue — at each stage of the funnel.", quote: "" },
  { nav: "Signal Intelligence", eyebrow: "Chapter 08 — Signal Intelligence", title: <>Act on the right signal <em>at the right moment.</em></>, body: "Signals tell us when to act. Instead of treating every customer or prospect the same, we monitor market, account, and contact-level activity to understand when there is a real reason to engage — and when waiting means losing.", quote: "Instead of treating every customer or prospect the same, we monitor market, account, and contact-level activity to understand when there is a reason to engage." },
  { nav: "Campaign Activation", eyebrow: "Chapter 09 — Campaign Activation", title: <>From signal to <em>coordinated action.</em></>, body: "Once a signal is detected, the system turns insight into action. Marketing builds the message, advertising amplifies it, and sales receives a clear motion — who to contact, why now, and what to say. The public funding signal becomes a real campaign example here.", quote: "Marketing builds the message, advertising amplifies it, and sales receives a clear motion for who to contact, why now, and what to say." },
  { nav: "Sales Motion", eyebrow: "Chapter 10 — Sales Motion", title: <>Sales execution built on the <em>same intelligence.</em></>, body: "The same segmentation, TAM, tiering, and signals that power marketing should also power sales execution. Account assignment, territory coverage, seller prioritization, and talk tracks all connect back to the customer segment, opportunity tier, and active signals.", quote: "Sales motions become stronger when they are built from the same intelligence layer as marketing." },
  { nav: "M+S Alignment", eyebrow: "Chapter 11 — Marketing + Sales Alignment", title: <>One system. <em>Two engines.</em></>, body: "The power of this model is alignment. Marketing and sales are not working from separate plans. They are operating from the same KPI framework, the same customer intelligence, and the same market opportunity model — feeding performance back into the executive dashboard together.", quote: "Marketing and sales are not working from separate plans. They are operating from the same intelligence layer." },
  { nav: "Return to Dashboard", eyebrow: "Chapter 12 — Performance Layer", title: <>Back to the dashboard. <em>Now it means something.</em></>, body: "We return to where we started — but the dashboard looks different now. Every KPI has a system behind it: a segment it belongs to, a tier it represents, a signal that activated it, and a campaign or sales motion that drove it. The dashboard is the performance layer of a complete commercial system.", quote: "The dashboard is not the starting point and it is not the strategy by itself. It is the performance layer of a complete commercial system." },
];

const styles = `
.commercial-page{--green:#4a9e7a;--green-pale:#edf6f1;--ink:#111;--body:#444;--muted:#888;--rule:#e8e8e8;--surface:#f7f7f7;--sig-g:#2e7d52;--sig-a:#b45309;--sig-r:#b91c1c;height:100vh;overflow:hidden;background:#fff;color:var(--ink);font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;}
.commercial-page *{box-sizing:border-box;}
.cs-nav{position:fixed;top:0;left:0;right:0;height:56px;background:#fff;border-bottom:1px solid var(--rule);display:flex;align-items:center;justify-content:space-between;padding:0 32px;z-index:50;}
.cs-logo{font-size:17px;font-weight:800;color:var(--ink);letter-spacing:-.3px;text-decoration:none;}.cs-logo em{font-style:italic;color:var(--green)}
.cs-links{display:flex;gap:28px;align-items:center}.cs-links a{font-size:10px;font-weight:700;letter-spacing:1.1px;text-transform:uppercase;text-decoration:none;color:var(--muted)}.cs-links a.active{color:var(--green)}
.cs-progress{position:fixed;top:56px;left:220px;right:0;height:2px;background:var(--rule);z-index:45}.cs-progress-fill{height:100%;background:var(--green);transition:width .25s ease}
.cs-shell{display:flex;height:100vh;padding-top:56px}.cs-rail{width:220px;flex-shrink:0;border-right:1px solid var(--rule);padding:28px 20px;overflow-y:auto;background:#fff}.rail-item{width:100%;display:flex;align-items:flex-start;gap:10px;padding:8px 10px;border:0;border-radius:4px;background:transparent;cursor:pointer;text-align:left}.rail-item:hover{background:var(--surface)}.rail-item.active{background:var(--green-pale)}.rail-dot{width:8px;height:8px;border-radius:999px;border:2px solid var(--rule);background:#fff;flex-shrink:0;margin-top:4px}.rail-item.done .rail-dot{background:var(--green);border-color:var(--green);opacity:.42}.rail-item.active .rail-dot{background:var(--green);border-color:var(--green);opacity:1}.rail-label{font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.7px;color:var(--muted);line-height:1.35}.rail-item.active .rail-label{color:var(--green)}.rail-connector{width:1px;height:10px;background:var(--rule);margin-left:23px}
.cs-stage-area{flex:1;overflow-y:auto;padding:40px 48px 116px;background:#fff}.cs-stage{max-width:none;margin:0}.stage-eyebrow{font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:1.2px;color:var(--green);margin-bottom:12px}.stage-title{font-size:32px;font-weight:800;line-height:1.1;letter-spacing:-.5px;margin:0 0 8px;color:var(--ink);max-width:900px}.stage-title em{font-style:italic;color:var(--green)}.stage-body{font-size:14px;line-height:1.7;color:var(--body);max-width:760px;margin:0 0 32px}.stage-quote{font-size:13px;font-style:italic;color:var(--muted);border-left:3px solid var(--green);padding-left:16px;margin:0 0 28px;line-height:1.65;max-width:700px}
.cs-footer{position:fixed;bottom:0;right:0;width:calc(100% - 220px);background:#fff;border-top:1px solid var(--rule);padding:16px 48px;display:flex;align-items:center;justify-content:space-between;z-index:45}.stage-counter{font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.8px;color:var(--muted)}.btns{display:flex;gap:10px}.cs-btn{padding:9px 22px;font-size:11px;font-weight:800;letter-spacing:.8px;text-transform:uppercase;border-radius:3px;border:1px solid var(--rule);background:#fff;color:var(--muted);cursor:pointer}.cs-btn:disabled{opacity:.3;cursor:default}.cs-btn.next{background:var(--green);border-color:var(--green);color:#fff}.cs-btn.next:hover{background:#3a8a68}
.kpi-dash{display:grid;grid-template-columns:repeat(4,1fr);gap:1px;background:var(--rule);border:1px solid var(--rule);border-radius:4px;overflow:hidden;margin-bottom:24px}.kd-card{background:#fff;padding:16px 18px}.kd-eye,.section-eye{font-size:9px;font-weight:800;text-transform:uppercase;letter-spacing:1px;color:var(--muted);margin-bottom:8px}.kd-val{font-size:22px;font-weight:800;letter-spacing:-.5px;line-height:1;margin-bottom:4px}.kd-delta{font-size:10px;font-weight:600}.pos{color:var(--sig-g)}.warn{color:var(--sig-a)}.flat{color:var(--muted)}
.two-col{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:24px}.three-col{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-bottom:24px}.row-stack{display:flex;flex-direction:column;gap:8px}.simple-row{background:#fff;border:1px solid var(--rule);border-radius:4px;padding:12px 16px;display:flex;align-items:center;gap:10px;font-size:12px;font-weight:700;color:var(--ink)}.bullet{width:6px;height:6px;border-radius:999px;background:var(--green);flex-shrink:0}.bullet.blue{background:#2d6bcd}
.card{background:#fff;border:1px solid var(--rule);border-radius:4px;padding:20px}.card-eye{font-size:9px;font-weight:800;text-transform:uppercase;letter-spacing:1px;color:var(--muted);margin-bottom:8px}.card-title{font-size:14px;font-weight:800;margin-bottom:6px;color:var(--ink)}.card-body{font-size:12px;color:var(--body);line-height:1.55}.track{height:2px;background:var(--rule);border-radius:1px;margin:10px 0 4px}.track div{height:100%;background:var(--green)}.tiny{font-size:10px;color:var(--muted)}.tag{display:inline-block;margin-top:10px;font-size:9px;font-weight:800;text-transform:uppercase;letter-spacing:.7px;padding:3px 8px;border-radius:2px;background:var(--green-pale);color:var(--sig-g)}.tag.blue{background:#eef3fc;color:#2d6bcd}.tag.amber{background:#fef3c7;color:var(--sig-a)}.hint{font-size:11px;color:var(--muted)}
.tam-shell{border:1px solid var(--rule);border-radius:4px;overflow:hidden;margin-bottom:20px;position:relative;height:360px;background:#e8edf2}.tam-map{position:absolute;inset:0}.map-dot{position:absolute;border-radius:999px;box-shadow:0 1px 4px rgba(0,0,0,.25)}.tam-card{position:absolute;top:14px;right:14px;background:rgba(255,255,255,.97);border:1px solid var(--rule);padding:13px 16px;text-align:right;box-shadow:0 1px 5px rgba(0,0,0,.08)}.tam-card strong{font-size:26px;line-height:1;color:var(--green)}.tam-legend{position:absolute;bottom:12px;left:12px;background:rgba(255,255,255,.97);border:1px solid var(--rule);border-radius:3px;padding:10px 14px;display:flex;flex-direction:column;gap:5px}.tam-legend div{font-size:10px;color:var(--body);display:flex;align-items:center;gap:6px}.tam-legend span{width:8px;height:8px;border-radius:999px}.stat-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:1px;background:var(--rule);border:1px solid var(--rule);border-radius:4px;overflow:hidden}.stat{background:#fff;padding:14px 16px}.stat-value{font-size:22px;font-weight:800;line-height:1;color:var(--ink)}.stat-value.green{color:var(--green)}
.persona-primary{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:14px}.persona-card{border:1px solid var(--rule);border-radius:6px;overflow:hidden;background:#fff}.pc-photo{height:130px;background:linear-gradient(135deg,#e0ebe4,#c8dbd0);position:relative;display:flex;align-items:center;padding-left:90px}.pc-photo.blue{background:linear-gradient(135deg,#e4eaf0,#ccd6e0)}.pc-head{width:70px;height:70px;border-radius:999px;background:rgba(74,158,122,.6);position:absolute;left:90px;top:18px}.pc-photo.blue .pc-head{background:rgba(45,107,205,.55)}.pc-lines{width:260px;height:56px;margin-left:95px;border-radius:3px;background:rgba(255,255,255,.38);position:relative}.pc-lines:before{content:"";position:absolute;left:16px;right:16px;top:17px;height:2px;background:rgba(74,158,122,.26);box-shadow:0 16px 0 rgba(74,158,122,.18)}.pc-badge{position:absolute;bottom:10px;left:12px;background:var(--green);color:#fff;font-size:9px;font-weight:800;text-transform:uppercase;letter-spacing:.7px;padding:3px 8px;border-radius:2px}.pc-body{padding:14px 16px 16px}.pc-role{font-size:9px;font-weight:800;text-transform:uppercase;letter-spacing:1px;color:var(--green)}.pc-name{font-size:16px;font-weight:800;letter-spacing:-.3px}.pc-seg{font-size:10px;font-weight:800;color:var(--muted);text-transform:uppercase;letter-spacing:.6px;margin-bottom:10px;padding-bottom:9px;border-bottom:1px solid var(--rule)}.pc-row{display:flex;gap:8px;margin:6px 0}.pc-key{font-size:9px;font-weight:800;text-transform:uppercase;letter-spacing:.5px;color:var(--muted);min-width:52px}.pc-val{font-size:11px;color:var(--body);line-height:1.4}.persona-secondary{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.sm-card{border:1px solid var(--rule);border-radius:4px;padding:14px 15px;background:#fff}.strip{height:4px;border-radius:2px;margin-bottom:10px}.sm-role{font-size:9px;font-weight:800;text-transform:uppercase;letter-spacing:1px;color:var(--green)}.sm-name{font-size:12px;font-weight:800;margin-bottom:6px}
.tier-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;background:var(--rule);border:1px solid var(--rule);border-radius:4px;overflow:hidden}.tier-card{background:#fff;padding:20px}.tier-num{font-size:28px;font-weight:800;letter-spacing:-1px}.tier-num.green{color:var(--green)}.tier-label{font-size:9px;font-weight:800;text-transform:uppercase;letter-spacing:1px;color:var(--muted)}.tier-seg{font-size:12px;font-weight:800;margin-bottom:8px;padding-bottom:8px;border-bottom:1px solid var(--rule)}.tier-desc{font-size:11px;color:var(--body);line-height:1.55;margin-bottom:10px}.tier-card ul,.sales-list{list-style:none;margin:0;padding:0;display:flex;flex-direction:column;gap:4px}.tier-card li,.sales-list li{font-size:11px;color:var(--muted);padding-left:12px;position:relative}.tier-card li:before,.sales-list li:before{content:'›';position:absolute;left:0;color:var(--green);font-weight:800}
.funnel-layout{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-bottom:20px;align-items:start}.funnel-list{border:1px solid var(--rule);border-radius:4px;overflow:hidden}.funnel-row{background:#fff;border-bottom:1px solid var(--rule);padding:10px 14px;display:flex;align-items:center;justify-content:space-between}.funnel-row:last-child{border-bottom:0;background:var(--green-pale)}.funnel-num{font-size:15px;font-weight:800}.funnel-note{font-size:10px;color:var(--muted)}.funnel-note.green{color:var(--green);font-weight:800}.funnel-svg{width:100%;display:block;max-height:660px}.signals{display:grid;grid-template-columns:1fr 1fr;gap:16px}.signal-card{border:1px solid var(--rule);border-radius:4px;overflow:hidden;background:#fff;margin-bottom:16px}.signal-header{display:flex;align-items:center;gap:12px;padding:14px 18px;border-bottom:1px solid var(--rule)}.sig-icon{width:32px;height:32px;border-radius:999px;background:var(--green-pale);display:flex;align-items:center;justify-content:center}.sig-title{font-size:13px;font-weight:800}.sig-sub{font-size:11px;color:var(--muted)}.sig-tag{margin-left:auto;font-size:9px;font-weight:800;text-transform:uppercase;letter-spacing:.7px;padding:3px 8px;border-radius:2px}.sig-body{background:var(--surface);padding:14px 18px;display:flex;gap:8px;align-items:center;flex-wrap:wrap}.sig-step{font-size:10px;font-weight:700;color:var(--body);padding:4px 10px;background:#fff;border:1px solid var(--rule);border-radius:2px}.sig-arrow{font-size:12px;color:#ccc}
.campaign{border:1px solid var(--rule);border-radius:4px;overflow:hidden}.campaign-head{background:#111;color:#fff;padding:12px 20px;font-size:11px;font-weight:800;text-transform:uppercase;letter-spacing:.8px}.campaign-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:1px;background:var(--rule)}.campaign-cell{background:#fff;padding:16px}.campaign-perf{background:var(--surface);padding:12px 20px;display:flex;gap:8px;align-items:center;flex-wrap:wrap}.sales-board{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;background:var(--rule);border:1px solid var(--rule);border-radius:4px;overflow:hidden}.sales-col{background:#fff}.sales-head{padding:12px 16px;border-bottom:1px solid var(--rule);background:var(--surface)}.sales-title{font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.8px}.sales-sub{font-size:10px;color:var(--muted)}.sales-list{padding:12px 16px;gap:0}.sales-list li{padding-top:8px;padding-bottom:8px;border-bottom:1px solid var(--surface);font-size:11px;color:var(--body)}
.align-grid{display:grid;grid-template-columns:1fr 180px 1fr;border:1px solid var(--rule);border-radius:4px;overflow:hidden}.align-side{background:#fff;padding:22px}.align-center{background:var(--green);padding:22px 14px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:6px;color:#fff;text-align:center}.align-center-label{font-size:9px;font-weight:800;text-transform:uppercase;letter-spacing:.8px;color:rgba(255,255,255,.7);margin-bottom:4px}.align-center-val{font-size:12px;font-weight:800}.align-sep{width:24px;height:1px;background:rgba(255,255,255,.25)}.align-item{font-size:11px;color:var(--body);padding:5px 0;border-bottom:1px solid var(--surface);display:flex;align-items:center;gap:6px}.align-item:before{content:'';width:5px;height:5px;border-radius:999px;background:var(--green);flex-shrink:0}.return-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:1px;background:var(--rule);border:1px solid var(--rule);border-radius:4px;overflow:hidden;margin-bottom:16px}.rg-card{background:#fff;padding:14px 16px}.rg-layer{font-size:9px;font-weight:800;text-transform:uppercase;letter-spacing:.7px;color:var(--green)}.rg-kpi{font-size:11px;font-weight:800}.rg-source{font-size:10px;color:var(--muted)}.system-flow{display:flex;flex-direction:column;gap:2px}.sys-row{display:flex;align-items:center;border:1px solid var(--rule);border-radius:3px;overflow:hidden}.sys-label{background:#111;color:#fff;font-size:9px;font-weight:800;text-transform:uppercase;letter-spacing:.8px;padding:8px 14px;min-width:160px}.sys-item{font-size:10px;color:var(--body);padding:8px 14px;border-left:1px solid var(--rule)}.final-box{padding:20px;background:var(--green-pale);border:1px solid var(--green);border-radius:4px;margin-top:20px}.final-box-title{font-size:11px;font-weight:800;text-transform:uppercase;letter-spacing:.8px;color:var(--green);margin-bottom:8px}.final-box p{font-size:14px;line-height:1.65;font-weight:600;margin:0;color:var(--ink)}
@media(max-width:1000px){.cs-links{display:none}.cs-rail{display:none}.cs-progress{left:0}.cs-footer{width:100%;padding:14px 20px}.cs-stage-area{padding:32px 20px 110px}.two-col,.three-col,.persona-primary,.persona-secondary,.funnel-layout,.signals,.campaign-grid,.sales-board,.align-grid,.return-grid,.tier-grid,.stat-grid{grid-template-columns:1fr}.stage-title{font-size:30px}}
`;

function KpiDashboard() {
  const rows = [["Revenue Growth", "14.3%", "▲ Above 12% target", "pos"], ["Market Share", "18.0%", "▲ Acct-based share", "pos"], ["Customer Acquisition", "196", "▲ New customers TTM", "pos"], ["Net Revenue Retention", "108%", "▲ Expanding base", "pos"], ["Pipeline Contribution", "$27.8M", "3.2× coverage ratio", "flat"], ["Sales Conversion", "31.9%", "▼ Below 38% target", "warn"], ["Customer LTV", "$23.1K", "▲ Exceeds $20K goal", "pos"], ["Marketing ROI", "5.0×", "▲ Above 4.5× target", "pos"]];
  return <><div className="kpi-dash">{rows.map(([a,b,c,d]) => <div className="kd-card" key={a}><div className="kd-eye">{a}</div><div className="kd-val">{b}</div><div className={`kd-delta ${d}`}>{c}</div></div>)}</div><p className="hint">These eight outcomes anchor every layer of the commercial system. Click <strong>Next</strong> to begin building the strategy beneath them.</p></>;
}

function GrowthObjective() {
  return <div className="two-col"><div><div className="section-eye">Business Outcome</div><div className="row-stack">{["Revenue growth","Market share expansion","New customer acquisition","Customer retention & expansion","Profitability improvement"].map(x => <div className="simple-row" key={x}><span className="bullet" />{x}</div>)}</div></div><div><div className="section-eye">Audience Focus</div><div className="row-stack">{["Customer segments by value","High-fit prospect segments","Industries & verticals","Territories & geographies","Accounts & buying contacts"].map(x => <div className="simple-row" key={x}><span className="bullet blue" />{x}</div>)}</div></div></div>;
}

function Segmentation() {
  const cards = [["Segment A","High-Value Existing Customers","Top-tier accounts by revenue and category breadth. Strong relationship depth and repurchase behavior.","Opportunity size: High","90%","Expand & Retain",""],["Segment B","Mid-Tier Growth Customers","Strong fit, moderate purchase frequency. Significant potential to expand category penetration.","Opportunity size: Medium–High","62%","Move Tier 3 → Tier 2","blue"],["Segment C","High-Fit Prospects","Not yet customers. Strong fit by industry, size, and buying profile. Highest new revenue potential.","Opportunity size: Large","45%","Acquire","amber"]];
  return <><div className="three-col">{cards.map(([eye,title,body,note,width,tag,color]) => <div className="card" key={title}><div className="card-eye">{eye}</div><div className="card-title">{title}</div><div className="card-body">{body}</div><div className="track"><div style={{width}} /></div><div className="tiny">{note}</div><span className={`tag ${color}`}>{tag}</span></div>)}</div><p className="hint">Click each segment to reveal the recommended commercial motion.</p></>;
}

function Tam() {
  const dots = useMemo(() => Array.from({ length: 86 }, (_, i) => ({ left: 18 + ((i * 37) % 76), top: 8 + ((i * 61) % 84), size: i % 5 === 0 ? 10 : i % 3 === 0 ? 8 : 5, color: i % 7 === 0 ? "#e8a020" : i % 5 === 0 ? "#2a72d5" : i % 4 === 0 ? "#3baf9e" : "#9eaab8" })), []);
  return <><div className="tam-shell"><svg className="tam-map" viewBox="0 0 900 360" preserveAspectRatio="none"><rect width="900" height="360" fill="#5a6170"/><path d="M900 0v360H145c-7-20-17-42-27-55-12-15-24-18-18-31l15-27c5-12-8-23-20-19l-22 7c-17 5-27-21-15-34l20-19c11-11 3-27-10-36-20-16 0-51 31-45 21 3 37-7 44-21 8-17-26-36 5-61 22-18 48-10 64-19z" fill="#e4e0d8"/><path d="M160 62h740M150 138h750M140 180h760M135 258h765M148 328h752M210 8v352M370 8v352M520 8v352M680 8v352M830 8v352" stroke="#f5f2ec" strokeWidth="4"/><path d="M170 100h730M160 160h740M155 220h745M290 8v352M445 8v352M600 8v352M755 8v352" stroke="#eeeae2" strokeWidth="2"/><path d="M165 50q135 60 205 88 80 27 150 40 70 12 160 22 70 8 150 15" stroke="#f0ece4" strokeWidth="3" fill="none"/><text x="255" y="128" fontSize="10" fill="#9c9288">Northgate</text><text x="390" y="128" fontSize="12" fill="#8a8078">Central District</text><text x="555" y="128" fontSize="10" fill="#9c9288">Eastside</text><text x="695" y="128" fontSize="10" fill="#9c9288">Hillcrest</text><text x="840" y="128" fontSize="10" fill="#9c9288">Ridgeline</text><text x="200" y="248" fontSize="10" fill="#9c9288">Bayside</text><text x="380" y="248" fontSize="10" fill="#9c9288">Midtown</text><text x="555" y="248" fontSize="10" fill="#9c9288">Southpark</text><text x="700" y="248" fontSize="10" fill="#9c9288">Valleyview</text><text x="840" y="248" fontSize="10" fill="#9c9288">Farpoint</text><text x="25" y="210" fontSize="10" fill="#9aaabb" transform="rotate(-75,25,210)">COASTAL BAY</text></svg>{dots.map((d,i) => <span key={i} className="map-dot" style={{ left:`${d.left}%`, top:`${d.top}%`, width:d.size, height:d.size, background:d.color }} />)}<div className="tam-card"><strong>895</strong><div className="section-eye" style={{marginTop:4}}>Addressable accounts</div><div className="tiny">161 active · 420 leads</div></div><div className="tam-legend"><div><span style={{background:'#2a72d5'}}/>Active customer</div><div><span style={{background:'#3baf9e'}}/>Engaged / recent</div><div><span style={{background:'#9eaab8'}}/>Lead / prospect</div><div><span style={{background:'#e8a020'}}/>Lapsed</div></div></div><div className="stat-grid">{[["Total Market","895","Addressable accounts",false],["Active Customers","161","18% account share",true],["Warm Pipeline","314","Engaged + outreach",false],["Whitespace","420","Unworked leads",false]].map(([a,b,c,g]) => <div className="stat" key={a as string}><div className="section-eye">{a}</div><div className={`stat-value ${g ? 'green' : ''}`}>{b}</div><div className="tiny">{c}</div></div>)}</div></>;
}

function Personas() {
  return <><div className="persona-primary"><PersonaCard blue={false} role="Decision-Maker" name="Executive Buyer" seg="High-Value Existing Customers · Segment A" badge="Primary Segment · A" rows={[['Priority','Revenue growth, competitive position, operational efficiency'],['Trigger','Board pressure, competitor moves, market expansion opportunity'],['Message','Business outcomes, ROI, strategic fit with growth agenda'],['Barrier','Risk aversion, incumbent relationships, approval cycles']]} /><PersonaCard blue role="Operational Buyer" name="Category / Ops Manager" seg="Mid-Tier Growth Customers · Segment B" badge="Primary Segment · B" rows={[['Priority','Supplier reliability, ease of ordering, product availability'],['Trigger','Stockouts, supplier issues, new product category need'],['Message','Availability, service levels, category depth and breadth'],['Barrier','Process inertia, comfort with existing vendor relationships']]} /></div><div className="section-eye">Supporting Personas</div><div className="persona-secondary"><SmallPersona strip="#f59e0b" role="Financial Approver" name="CFO / Finance Lead" rows={[['Priority','Cost control, payment terms, total cost of ownership'],['Message','Price competitiveness, consolidated billing, savings'],['Barrier','Switching cost perception, internal approval process']]} /><SmallPersona strip="#7c3aed" role="Technical Evaluator" name="Procurement / Spec Lead" rows={[['Priority','Product specs, compliance standards, quality assurance'],['Message','Technical depth, certifications, dedicated support'],['Barrier','Spec lock-in, long technical evaluation cycles']]} /><SmallPersona strip="#4a9e7a" role="Influencer / End User" name="Field / Project Team" rows={[['Priority','Ease of use, product availability, delivery speed'],['Message','Speed, reliability, familiar and trusted brands'],['Barrier','Habit, familiarity with current tools and workflow']]} /></div></>;
}
function PersonaCard({ blue, role, name, seg, badge, rows }: { blue?: boolean; role:string; name:string; seg:string; badge:string; rows:string[][] }) { return <div className="persona-card"><div className={`pc-photo ${blue ? 'blue' : ''}`}><div className="pc-head"/><div className="pc-lines"/><div className="pc-badge">{badge}</div></div><div className="pc-body"><div className="pc-role">{role}</div><div className="pc-name">{name}</div><div className="pc-seg">{seg}</div>{rows.map(([k,v]) => <div className="pc-row" key={k}><div className="pc-key">{k}</div><div className="pc-val">{v}</div></div>)}</div></div> }
function SmallPersona({ strip, role, name, rows }: { strip:string; role:string; name:string; rows:string[][] }) { return <div className="sm-card"><div className="strip" style={{background:strip, opacity:.45}}/><div className="sm-role">{role}</div><div className="sm-name">{name}</div>{rows.map(([k,v]) => <div className="pc-row" key={k}><div className="pc-key">{k}</div><div className="pc-val">{v}</div></div>)}</div> }

function Tiering() { const cards = [["T1","Highest-Value Customers","Segment A — High-Value Accounts","Largest revenue contribution, broadest category footprint, deepest relationship. Alexandra and buyers like her are here. Protect and grow at all costs.",["Executive relationship management","Strategic account plans on file","Loyalty & retention campaigns","Proactive cross-sell by senior seller","Early access to new products"]],["T2","Growth Customers","Segment B — Mid-Tier Accounts","Good fit, solid revenue, underpenetrated category. Marcus and ops-focused buyers live here. Clear path to Tier 1 with the right motion and category expansion play.",["Category expansion campaigns","Personalized cross-sell offers","Seller-assisted growth plays","Lifecycle nurture sequences","Reorder reminders, usage signals"]],["T3","Underdeveloped Customers","Segment C — Early Relationship","Low purchase frequency or narrow category use. The relationship exists but full potential is unrealized. Procurement and field personas often enter here and need education-first motions.",["Re-engagement campaigns","Product & category education","Category introduction sequences","Automated nurture tracks","Win-back with targeted incentive"]]] as const; return <div className="tier-grid">{cards.map(([n,l,s,d,items]) => <div className="tier-card" key={n}><div className={`tier-num ${n === 'T1' ? 'green' : ''}`}>{n}</div><div className="tier-label">{l}</div><div className="tier-seg">{s}</div><div className="tier-desc">{d}</div><ul>{items.map(i => <li key={i}>{i}</li>)}</ul></div>)}</div> }

function Funnel() { const rows = [["Market Reach","2.4M","Total impressions"],["Leads","12,400","Identified accounts"],["MQL","3,840","31% of leads"],["SQL","1,228","MQL→SQL 32%"],["Opportunity","614","SQL→Opp 50%"],["Closed Won","196","Win rate 31.9%"],["Revenue","$84.2M","TTM closed revenue"]]; return <><div className="funnel-layout"><div><div className="section-eye">Funnel Stage Breakdown</div><div className="funnel-list">{rows.map(([a,b,c],i) => <div className="funnel-row" key={a}><div><div className="section-eye" style={{marginBottom:1}}>{a}</div><div className="funnel-num">{b}</div></div><div className={`funnel-note ${i>1?'green':''}`}>{c}</div></div>)}</div></div><div><div className="section-eye">Conversion Funnel</div><FunnelSvg /></div></div><div className="three-col"><div className="card"><div className="card-eye">Tier 1 Prospects</div><div className="card-title">High-fit · High-value</div><div className="card-body">Account-based selling, direct outreach, priority sales assignment, executive access plays.</div><span className="tag">Actively pursue</span></div><div className="card"><div className="card-eye">Tier 2 Prospects</div><div className="card-title">Strong fit · Needs nurture</div><div className="card-body">Demand generation campaigns, content nurture, intent monitoring, seller follow-up on signal.</div><span className="tag blue">Nurture to SQL</span></div><div className="card"><div className="card-eye">Tier 3 Prospects</div><div className="card-title">Early-stage · Lower fit</div><div className="card-body">Broad awareness, category education, low-cost digital programs. Move to Tier 2 on engagement signal.</div><span className="tag amber">Qualify and Promote</span></div></div></> }
function FunnelSvg() { return <svg className="funnel-svg" viewBox="0 0 280 380"><polygon points="10,0 270,0 250,52 30,52" fill="#e8f0ea"/><polygon points="30,56 250,56 234,106 46,106" fill="#dde9e3"/><polygon points="46,110 234,110 218,158 62,158" fill="#cfdfc8"/><polygon points="62,162 218,162 202,210 78,210" fill="#b8d4b0"/><polygon points="78,214 202,214 186,262 94,262" fill="#8ec49e"/><polygon points="94,266 186,266 172,314 108,314" fill="#5aac78"/><polygon points="108,318 172,318 156,360 124,360" fill="#4a9e7a"/><text x="140" y="25" textAnchor="middle" fontSize="14" fontWeight="800" fill="#888">MARKET REACH</text><text x="140" y="42" textAnchor="middle" fontSize="18" fontWeight="800">2.4M</text><text x="140" y="80" textAnchor="middle" fontSize="14" fontWeight="800" fill="#888">LEADS</text><text x="140" y="97" textAnchor="middle" fontSize="18" fontWeight="800">12,400</text><text x="140" y="134" textAnchor="middle" fontSize="14" fontWeight="800" fill="#888">MQL</text><text x="140" y="151" textAnchor="middle" fontSize="18" fontWeight="800">3,840</text><text x="140" y="186" textAnchor="middle" fontSize="14" fontWeight="800" fill="#555">SQL</text><text x="140" y="203" textAnchor="middle" fontSize="18" fontWeight="800">1,228</text><text x="140" y="238" textAnchor="middle" fontSize="14" fontWeight="800" fill="#555">OPPORTUNITY</text><text x="140" y="255" textAnchor="middle" fontSize="18" fontWeight="800">614</text><text x="140" y="288" textAnchor="middle" fontSize="14" fontWeight="800" fill="#fff">CLOSED WON</text><text x="140" y="306" textAnchor="middle" fontSize="18" fontWeight="800" fill="#fff">196</text><text x="140" y="345" textAnchor="middle" fontSize="15" fontWeight="800" fill="#fff">$84.2M</text><text x="264" y="132" fontSize="10" fill="#4a9e7a" fontWeight="800">31%</text><text x="264" y="186" fontSize="10" fill="#4a9e7a" fontWeight="800">32%</text><text x="264" y="238" fontSize="10" fill="#4a9e7a" fontWeight="800">50%</text><text x="264" y="290" fontSize="10" fill="#4a9e7a" fontWeight="800">32%</text></svg> }

function Signals() { const blocks = [["Customer Signals",[["↘","Declining Purchase Frequency","Spend down 30%+ vs. prior quarter","At Risk",['Signal','Alert seller','Re-engagement offer','Track recovery'],'red'],["🛒","Cross-Sell Opportunity","High-value customer buying in only 1 of 4 categories","Expand",['Signal','Personalized offer','Seller play','Measure lift'],'blue']]],["Prospect Signals",[["💰","Public Funding Received","14 target accounts awarded contracts this quarter","Act Now",['Signal detected','Accounts matched','Campaign launched','Sales alerted'],'green'],["🔍","Intent Signal Detected","Prospect actively searching category keywords","Engage",['Signal','Retargeting on','Sales priority ↑','Track conversion'],'amber']]]]; return <div className="signals">{blocks.map(([label,items]) => <div key={label as string}><div className="section-eye">{label}</div>{(items as any[]).map(([icon,title,sub,tag,steps,color]) => <div className="signal-card" key={title}><div className="signal-header"><div className="sig-icon">{icon}</div><div><div className="sig-title">{title}</div><div className="sig-sub">{sub}</div></div><span className={`sig-tag tag ${color==='red'?'amber':color}`}>{tag}</span></div><div className="sig-body">{steps.map((s:string,idx:number) => <><span className="sig-step" key={s}>{s}</span>{idx < steps.length-1 && <span className="sig-arrow" key={`${s}-a`}>→</span>}</>)}</div></div>)}</div>)}</div> }
function Campaign() { return <div className="campaign"><div className="campaign-head">Campaign: Public Funding Recipients — Q4 Outreach</div><div className="campaign-grid">{[["01 Audience","14 funded accounts","Matched to TAM · Tier 1 & 2 prospects · 38 contacts identified"],["02 Message","\"Your funding. Your move.\"","Segment-specific landing page · Ops buyer persona · Urgency-led offer"],["03 Channels","Email + LinkedIn + Display","Retargeting active · Sales email sequence · Direct mail for top 5 accounts"],["04 Sales Handoff","CRM tasks created","Sellers assigned · Talk track delivered · Pipeline stage: Qualified"]].map(([a,b,c]) => <div className="campaign-cell" key={a}><div className="rg-layer">{a}</div><div className="card-title">{b}</div><div className="card-body">{c}</div></div>)}</div><div className="campaign-perf"><span className="section-eye" style={{marginBottom:0}}>Performance:</span>{["Open rate 34%","3 SQLs in week 1","$280K pipeline created","1 closed in 28 days"].map(x => <span className="sig-step" key={x}>{x}</span>)}</div></div> }
function Sales() { const cols = [["Tier 1 Accounts","Protect · Grow · Retain",["Assigned to senior sellers","Weekly executive touchpoints","Strategic account plans on file","Talk track: Value expansion, loyalty","KPI: NRR, LTV growth, wallet share"]],["Tier 2 Accounts","Expand · Cross-sell · Develop",["Mid-market sellers assigned","Signal-triggered outreach","Category expansion playbooks","Talk track: New category intro, offers","KPI: Revenue per account, pipeline"]],["Tier 1 Prospects","Acquire · Convert · Close",["AE-assigned, high-priority","Multi-contact account plays","Campaign context in CRM","Talk track: Problem, urgency, fit","KPI: Win rate, CAC payback, revenue"]]]; return <div className="sales-board">{cols.map(([title,sub,items]) => <div className="sales-col" key={title as string}><div className="sales-head"><div className="sales-title">{title}</div><div className="sales-sub">{sub}</div></div><ul className="sales-list">{(items as string[]).map(i => <li key={i}>{i}</li>)}</ul></div>)}</div> }
function Alignment() { return <div className="align-grid"><div className="align-side"><div className="section-eye">Marketing Outputs</div>{["Segment-targeted campaigns","Demand generation & content","Paid media & retargeting","MQL creation & scoring","Lead nurture sequences","Signal-triggered activation","Marketing pipeline (MQL→SQL)","Campaign ROI measurement"].map(x => <div className="align-item" key={x}>{x}</div>)}</div><div className="align-center"><div className="align-center-label">Shared Intelligence Layer</div>{["KPI Framework","Segmentation","TAM + Personas","Tiering","Signals"].map(x => <><div className="align-sep"/><div className="align-center-val" key={x}>{x}</div></>)}</div><div className="align-side"><div className="section-eye">Sales Outputs</div>{["Account & territory assignment","Tier-based prioritization","Persona-matched talk tracks","Signal-driven outreach","Opportunity creation (SQL→Opp)","Pipeline stage progression","Closed-won revenue","Territory performance reporting"].map(x => <div className="align-item" key={x}>{x}</div>)}</div></div> }
function ReturnDashboard() { const data = [["Segmentation + TAM","Market Share: 18.0%","161 active of 895 addressable accounts"],["Customer Tiering","Revenue Growth: 14.3%","Tier 1 expansion + new acquisition"],["Prospect Funnel","Pipeline: $27.8M","3.2× coverage · 614 active opportunities"],["Campaign Activation","Marketing ROI: 5.0×","$31.2M sourced on $6.2M spend"],["Sales Motion","Win Rate: 31.9%","196 closed-won · improving with playbooks"],["Signal Intelligence","MQL→SQL: 32%","Signal-triggered lift vs. broadcast average"],["Personas + Tiering","LTV: $23.1K","Expansion motions moving T2→T1"],["Full System","NRR: 108%","Customers expanding faster than churn"]]; return <><div className="return-grid">{data.map(([a,b,c]) => <div className="rg-card" key={a}><div className="rg-layer">{a}</div><div className="rg-kpi">{b}</div><div className="rg-source">{c}</div></div>)}</div><div className="system-flow">{[["Executive KPIs",["Revenue growth","Market share","Acquisition","Expansion","Profitability"]],["Intelligence Layer",["Segmentation","TAM + whitespace","Personas","Customer tiering","Signal monitoring"]],["Marketing Engine",["Demand generation","Campaign activation","MQL creation","Nurture","Measurement"]],["Sales Engine",["Account prioritization","Territory motions","Talk tracks","Pipeline management","Closed-won revenue"]]].map(([label,items]) => <div className="sys-row" key={label as string}><div className="sys-label">{label}</div>{(items as string[]).map(x => <div className="sys-item" key={x}>{x}</div>)}</div>)}</div><div className="final-box"><div className="final-box-title">The complete system</div><p>This is how we move from executive goals to market intelligence, from market intelligence to marketing and sales action, and from action back to measurable business performance.</p></div></> }

function StageContent({ current }: { current: number }) {
  if (current === 0) return <KpiDashboard />;
  if (current === 1) return <GrowthObjective />;
  if (current === 2) return <Segmentation />;
  if (current === 3) return <Tam />;
  if (current === 4) return <Personas />;
  if (current === 5) return <Tiering />;
  if (current === 6) return <Funnel />;
  if (current === 7) return <Signals />;
  if (current === 8) return <Campaign />;
  if (current === 9) return <Sales />;
  if (current === 10) return <Alignment />;
  return <ReturnDashboard />;
}

export default function CommercialStrategyPage() {
  const [current, setCurrent] = useState(0);
  const stage = stages[current];
  const pct = ((current + 1) / stages.length) * 100;
  const goTo = (idx: number) => setCurrent(Math.max(0, Math.min(stages.length - 1, idx)));
  const nav = (dir: number) => current === stages.length - 1 && dir > 0 ? setCurrent(0) : goTo(current + dir);

  return <main className="commercial-page"><style>{styles}</style><nav className="cs-nav"><a className="cs-logo" href="/">About <em>Chad</em></a><div className="cs-links"><a href="/">About</a><a href="/approach">My Approach</a><a href="/career">Career</a><a href="/skills">Skills</a><a className="active" href="/commercial-strategy">Work Samples</a><a href="/contact">Contact</a></div></nav><div className="cs-progress"><div className="cs-progress-fill" style={{ width: `${pct}%` }} /></div><div className="cs-shell"><aside className="cs-rail">{stages.map((s, i) => <div key={s.nav}>{i > 0 && <div className="rail-connector" />}<button onClick={() => goTo(i)} className={`rail-item ${i === current ? 'active' : ''} ${i < current ? 'done' : ''}`}><span className="rail-dot" /><span className="rail-label">{s.nav}</span></button></div>)}</aside><section className="cs-stage-area"><div className="cs-stage"><div className="stage-eyebrow">{stage.eyebrow}</div><h1 className="stage-title">{stage.title}</h1><p className="stage-body">{stage.body}</p>{stage.quote && <div className="stage-quote">&quot;{stage.quote}&quot;</div>}<StageContent current={current} /></div></section></div><footer className="cs-footer"><div className="stage-counter">Chapter {current + 1} of {stages.length}</div><div className="btns"><button className="cs-btn" onClick={() => nav(-1)} disabled={current === 0}>← Back</button><button className="cs-btn next" onClick={() => nav(1)}>{current === stages.length - 1 ? "↩ Start Over" : "Next →"}</button></div></footer></main>;
}
