-- Pulls in genuinely new companies/contacts found in the 'Target Accounts' and
-- 'Contacts' tabs of the same RevHub Target Accounts sheet (never synced before -
-- only RevHub-Marketing / RevHub-Marketing Signals had been synced until now).
--
-- LGG Industrial is a rename of the existing 'ERIKS North America' row (sheet
-- confirms: "corrected the account from the superseded ERIKS North America name
-- to LGG Industrial, its official name since February 1, 2024"). Its 3 existing
-- project_contacts rows under that name were empty placeholders (null name/title,
-- linkedin_url literally the string 'Search') from an earlier import, so they are
-- replaced with the 3 real, current contacts rather than kept alongside them.
--
-- Motion, DNOW, James Hardie, and Owens Corning are the CURRENT names for accounts
-- the sheet lists under old/acquired names (Kaman Distribution Group, MRC Global,
-- AZEK Company, Masonite respectively - all confirmed via M&A notes in the sheet).
-- Their contacts have no drafted messaging yet in the sheet, so they're inserted
-- as research-tier (name/title/linkedin only) rather than invented.
--
-- NOT included (flagged separately, needs a decision): Wolseley UK (explicit
-- QXO-adjacent exclusion, no valid targets), Envoy Solutions / H&E Equipment
-- Services (fully retired/redirected to BradyPLUS and Herc Rentals, which are
-- already fully synced), and Herc Rentals' updated canonical contact sequence
-- (Leslie Hunziker / Lawrence Silber / Aaron Birnbaum) which differs from the 3
-- contacts already tracked there (Matt Gavin / Rob Valerio / William Stec).

-- Rename ERIKS North America -> LGG Industrial (current official name)
update public.companies set
  name = $$LGG Industrial$$,
  normalized_name = $$lgg industrial$$,
  website = $$https://www.lggindustrial.com$$,
  updated_at = now()
where name = 'ERIKS North America';

-- Delete the 3 empty placeholder contacts under the old name
delete from public.project_contacts
where id in ('412bbae7-1172-4dce-b673-0df829613876', '12585909-782c-4555-9f24-fd9e2feaeeeb', '0b9fe149-f989-412d-94cc-033e7973cacb');

-- New companies
insert into public.companies (name, normalized_name, industry, sector, website) values ($$Landstar$$, $$landstar$$, $$Aviation & Logistics$$, $$Truckload / Dedicated / Logistics$$, $$https://www.landstar.com$$);
insert into public.companies (name, normalized_name, industry, sector, website) values ($$Motion$$, $$motion$$, $$Industrial Distribution$$, $$Industrial Parts Distribution$$, $$https://www.motion.com$$);
insert into public.companies (name, normalized_name, industry, sector, website) values ($$DNOW$$, $$dnow$$, $$Industrial Distribution$$, $$PVF Distribution$$, null);
insert into public.companies (name, normalized_name, industry, sector, website) values ($$James Hardie$$, $$james hardie$$, $$Industrial Manufacturing$$, $$Building Products Manufacturing$$, null);
insert into public.companies (name, normalized_name, industry, sector, website) values ($$Owens Corning$$, $$owens corning$$, $$Industrial Manufacturing$$, $$Building Products Manufacturing$$, null);

-- New contacts with full messaging (Landstar, LGG Industrial)
insert into public.project_contacts (company, company_id, contact_name, title, linkedin_url, priority, target_type_raw, outreach_angle, value_hypothesis, stakeholder_selection_reason, linkedin_connect_message) values ($$Landstar$$, (select id from public.companies where name = $$Landstar$$), $$Katie Mountain$$, $$Executive Vice President, Business Development$$, $$https://www.linkedin.com/in/katiemountain$$, $$A$$, $$Growth / Business Development Owner$$, $$Agency growth, customer development, service expansion, sales capability and commercial execution across Landstar's independent-agent network.$$, $$Landstar can accelerate profitable agency growth by connecting customer and lane intelligence, service adoption, sales activity, agent capability and network economics into one commercial operating cadence.$$, $$Marketing-first research did not surface a confirmed enterprise marketing executive. Katie is the highest-priority growth leader because her remit directly supports agency revenue expansion and business development.$$, $$Hi Katie, your work helping Landstar agencies expand revenue and capabilities stood out. I lead RevHub, helping logistics networks connect customer intelligence, commercial priorities and operating execution into one growth system. I would value connecting.$$);
insert into public.project_contacts (company, company_id, contact_name, title, linkedin_url, priority, target_type_raw, outreach_angle, value_hypothesis, stakeholder_selection_reason, linkedin_connect_message) values ($$Landstar$$, (select id from public.companies where name = $$Landstar$$), $$Matt Dannegger$$, $$Vice President and Chief Field Sales Officer$$, $$https://www.linkedin.com/in/matt-dannegger-21a12612$$, $$A$$, $$Sales / Agent Growth Owner$$, $$Field sales productivity, agent recruitment and development, cross-selling, customer growth and adoption of commercial tools and technology.$$, $$Landstar can improve field-sales productivity by connecting agent opportunities, customer potential, service mix, lane economics and tool adoption into clearer account and growth priorities.$$, $$Current official biography and direct profile align at high confidence; check currentness immediately before outreach.$$, $$Hi Matt, your field sales leadership across Landstar's agent network stood out. I lead RevHub, helping logistics businesses connect account intelligence, sales execution, pricing and network performance into one commercial growth system. I would value connecting.$$);
insert into public.project_contacts (company, company_id, contact_name, title, linkedin_url, priority, target_type_raw, outreach_angle, value_hypothesis, stakeholder_selection_reason, linkedin_connect_message) values ($$Landstar$$, (select id from public.companies where name = $$Landstar$$), $$James M. Applegate$$, $$Vice President and Chief Corporate Sales, Strategy and Specialized Freight Officer$$, $$https://www.linkedin.com/in/james-applegate-6586444$$, $$A$$, $$Commercial Strategy Owner$$, $$Corporate sales, strategic growth, specialized freight, customer solutions, business development and commercial analytics.$$, $$Landstar can strengthen corporate and specialized-freight growth by connecting customer segmentation, opportunity sizing, lane and capacity economics, solution design and sales execution into one decision system.$$, $$Current official role confirmation and high-confidence direct LinkedIn profile; exact title should be checked immediately before outreach.$$, $$Hi James, your leadership across corporate sales, strategy and specialized freight stood out. I lead RevHub, helping complex logistics businesses connect customer intelligence, pricing, commercial execution and operations into one growth system. I would value connecting.$$);
insert into public.project_contacts (company, company_id, contact_name, title, linkedin_url, priority, target_type_raw, outreach_angle, value_hypothesis, stakeholder_selection_reason, linkedin_connect_message) values ($$LGG Industrial$$, (select id from public.companies where name = $$LGG Industrial$$), $$Tim Billingsley$$, $$Vice President, Revenue Operations$$, $$https://www.linkedin.com/in/tim-billingsley$$, $$A$$, $$Revenue Marketing / Revenue Operations Owner$$, $$CRM, sales automation, customer intelligence, pipeline visibility and time-to-revenue acceleration.$$, $$LGG can build on its CRM transformation by connecting account segmentation, customer behavior, pipeline, pricing, branch activity and executive reporting into one commercial growth operating system.$$, $$Marketing-first search did not surface a current senior marketing executive. Tim is the highest-priority growth-system owner because his remit directly connects CRM, sales operations, customer visibility and revenue acceleration.$$, $$Hi Tim, your RevOps and CRM transformation work at LGG stood out. I lead RevHub, helping industrial distributors connect customer intelligence, pipeline, pricing and execution into one commercial growth system. I would value connecting.$$);
insert into public.project_contacts (company, company_id, contact_name, title, linkedin_url, priority, target_type_raw, outreach_angle, value_hypothesis, stakeholder_selection_reason, linkedin_connect_message) values ($$LGG Industrial$$, (select id from public.companies where name = $$LGG Industrial$$), $$Terry Subia$$, $$Vice President, Key Markets$$, $$https://www.linkedin.com/in/terry-subia-a27a5b157$$, $$A$$, $$Commercial / Strategic Accounts Owner$$, $$Strategic accounts, key-market growth, customer partnerships, cross-sell and regional commercial execution.$$, $$LGG can improve organic growth by connecting key-account potential, industry demand, product capabilities, pricing, branch service and relationship activity into clearer market and account priorities.$$, $$Prioritized behind Revenue Operations because Terry owns customer growth across key industrial markets and can sponsor segmentation, strategic-account and cross-sell improvements.$$, $$Hi Terry, your key-markets leadership and organic-growth focus at LGG stood out. I lead RevHub, helping industrial distributors connect customer segmentation, pricing, sales execution and branch performance into one growth system. I would value connecting.$$);
insert into public.project_contacts (company, company_id, contact_name, title, linkedin_url, priority, target_type_raw, outreach_angle, value_hypothesis, stakeholder_selection_reason, linkedin_connect_message) values ($$LGG Industrial$$, (select id from public.companies where name = $$LGG Industrial$$), $$Jeff Crane$$, $$Chief Executive Officer$$, $$https://www.linkedin.com/in/jeff-crane-64315a15$$, $$A$$, $$Executive Sponsor$$, $$Enterprise growth strategy, acquisition integration, technology modernization and commercial operating-model alignment.$$, $$LGG can unify its rebrand, CRM investment, branch network, acquisitions and organic-growth agenda through a shared commercial data foundation and operating cadence.$$, $$Executive sponsor retained as Target 3 behind the functional Revenue Operations and Key Markets leaders.$$, $$Hi Jeff, LGG’s rebrand, branch investment and organic-growth agenda stood out. I lead RevHub, helping industrial distributors connect customer intelligence, pricing, sales and operations into one commercial growth system. I would value connecting.$$);

-- New research-tier contacts (Motion, DNOW, James Hardie, Owens Corning) - no drafted
-- messaging exists in the sheet yet for these, so no linkedin_connect_message/
-- intro_message/follow_up_message is written.
insert into public.project_contacts (company, company_id, contact_name, title, linkedin_url, priority, outreach_angle, value_hypothesis) values ($$Motion$$, (select id from public.companies where name = $$Motion$$), $$James Howe$$, $$President, Motion$$, $$https://www.linkedin.com/in/jamesfhowe/$$, $$A$$, $$M&A integration; branch network; pricing discipline.$$, $$Industrial parts distribution has branch inventory, complex SKU mix, pricing, and account profitability challenges.$$);
insert into public.project_contacts (company, company_id, contact_name, title, linkedin_url, priority, outreach_angle, value_hypothesis) values ($$Motion$$, (select id from public.companies where name = $$Motion$$), $$William P. Stengel II$$, $$Chairman & Chief Executive Officer, Genuine Parts Company$$, $$https://www.linkedin.com/in/will-stengel-8334673$$, $$A$$, $$M&A integration; branch network; pricing discipline.$$, $$Industrial parts distribution has branch inventory, complex SKU mix, pricing, and account profitability challenges.$$);
insert into public.project_contacts (company, company_id, contact_name, title, linkedin_url, priority, outreach_angle, value_hypothesis) values ($$Motion$$, (select id from public.companies where name = $$Motion$$), $$Kevin Coons$$, $$Vice President of Procurement, Motion$$, $$https://www.linkedin.com/in/kevin-coons-7827a84$$, $$A$$, $$M&A integration; branch network; pricing discipline.$$, $$Industrial parts distribution has branch inventory, complex SKU mix, pricing, and account profitability challenges.$$);
insert into public.project_contacts (company, company_id, contact_name, title, linkedin_url, priority, outreach_angle, value_hypothesis) values ($$DNOW$$, (select id from public.companies where name = $$DNOW$$), $$Elaine Michael$$, $$Vice President, Marketing, DNOW$$, $$https://www.linkedin.com/in/emichael$$, $$B$$, $$Energy/industrial project demand; customer terms; margin control.$$, $$PVF distribution has complex SKU/customer terms, contract pricing, inventory, and project-driven demand challenges.$$);
insert into public.project_contacts (company, company_id, contact_name, title, linkedin_url, priority, outreach_angle, value_hypothesis) values ($$DNOW$$, (select id from public.companies where name = $$DNOW$$), $$Brad Wise$$, $$Vice President, Digital Strategy and Investor Relations$$, $$https://www.linkedin.com/in/brad-wise-b9011661$$, $$B$$, $$Energy/industrial project demand; customer terms; margin control.$$, $$PVF distribution has complex SKU/customer terms, contract pricing, inventory, and project-driven demand challenges.$$);
insert into public.project_contacts (company, company_id, contact_name, title, linkedin_url, priority, outreach_angle, value_hypothesis) values ($$DNOW$$, (select id from public.companies where name = $$DNOW$$), $$David Cherechinsky$$, $$President and Chief Executive Officer, DNOW$$, null, $$B$$, $$Energy/industrial project demand; customer terms; margin control.$$, $$PVF distribution has complex SKU/customer terms, contract pricing, inventory, and project-driven demand challenges.$$);
insert into public.project_contacts (company, company_id, contact_name, title, linkedin_url, priority, outreach_angle, value_hypothesis) values ($$James Hardie$$, (select id from public.companies where name = $$James Hardie$$), $$Samara (Sam) Toole$$, $$Chief Marketing Officer, James Hardie$$, $$https://www.linkedin.com/in/sam-toole$$, $$B$$, $$Channel strategy; pricing; customer segmentation.$$, $$B2B channel-heavy building products manufacturer with dealer/distributor pricing and demand planning needs.$$);
insert into public.project_contacts (company, company_id, contact_name, title, linkedin_url, priority, outreach_angle, value_hypothesis) values ($$James Hardie$$, (select id from public.companies where name = $$James Hardie$$), $$Aaron Erter$$, $$Chief Executive Officer, James Hardie$$, $$https://www.linkedin.com/in/aerter$$, $$B$$, $$Channel strategy; pricing; customer segmentation.$$, $$B2B channel-heavy building products manufacturer with dealer/distributor pricing and demand planning needs.$$);
insert into public.project_contacts (company, company_id, contact_name, title, linkedin_url, priority, outreach_angle, value_hypothesis) values ($$James Hardie$$, (select id from public.companies where name = $$James Hardie$$), $$Jon Skelly$$, $$President and General Manager, James Hardie North America Building Products Group$$, $$https://www.linkedin.com/in/jonskelly$$, $$B$$, $$Channel strategy; pricing; customer segmentation.$$, $$B2B channel-heavy building products manufacturer with dealer/distributor pricing and demand planning needs.$$);
insert into public.project_contacts (company, company_id, contact_name, title, linkedin_url, priority, outreach_angle, value_hypothesis) values ($$Owens Corning$$, (select id from public.companies where name = $$Owens Corning$$), $$Rachel Barthelemy Marcon$$, $$President, Doors, Owens Corning$$, $$https://www.linkedin.com/in/rachel-barthelemy-marcon-42511a53$$, $$B$$, $$Integration status; channel pricing; product mix profitability.$$, $$Manufacturer with distribution/channel, pricing, and product/customer profitability complexity.$$);
insert into public.project_contacts (company, company_id, contact_name, title, linkedin_url, priority, outreach_angle, value_hypothesis) values ($$Owens Corning$$, (select id from public.companies where name = $$Owens Corning$$), $$Brian Chambers$$, $$Chair and Chief Executive Officer, Owens Corning$$, $$https://www.linkedin.com/in/brian-chambers-6422617$$, $$B$$, $$Integration status; channel pricing; product mix profitability.$$, $$Manufacturer with distribution/channel, pricing, and product/customer profitability complexity.$$);
insert into public.project_contacts (company, company_id, contact_name, title, linkedin_url, priority, outreach_angle, value_hypothesis) values ($$Owens Corning$$, (select id from public.companies where name = $$Owens Corning$$), $$Todd Fister$$, $$Executive Vice President and Chief Financial and Operating Officer, Owens Corning$$, $$https://www.linkedin.com/in/toddfister$$, $$B$$, $$Integration status; channel pricing; product mix profitability.$$, $$Manufacturer with distribution/channel, pricing, and product/customer profitability complexity.$$);